(part "W25Q128JVPIQ_TR"
    (packageRef "SON127P600X500X80-9N-D")
    (interface
        (port "1" (symbPinId 1) (portName "%CS%") (portType INOUT))
        (port "2" (symbPinId 2) (portName "DO_(IO1)") (portType INOUT))
        (port "3" (symbPinId 3) (portName "%WP_(IO2)%") (portType INOUT))
        (port "4" (symbPinId 4) (portName "GND") (portType INOUT))
        (port "5" (symbPinId 5) (portName "DI_(IO0)") (portType INOUT))
        (port "6" (symbPinId 6) (portName "CLK") (portType INOUT))
        (port "7" (symbPinId 7) (portName "%HOLD_OR_RESET_(IO3)%") (portType INOUT))
        (port "8" (symbPinId 8) (portName "VCC") (portType INOUT))
        (port "9" (symbPinId 9) (portName "EP") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "101")
    (property "Mouser_Part_Number" "454-W25Q128JVPIQTR")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Winbond/W25Q128JVPIQ-TR?qs=qSfuJ%252Bfl%2Fd6H7vbXyrDu3w%3D%3D")
    (property "Manufacturer_Name" "Winbond")
    (property "Manufacturer_Part_Number" "W25Q128JVPIQ TR")
    (property "Description" "NOR Flash spiFlash, 3V, 128M-bit, 4Kb Uniform Sector")
    (property "Datasheet_Link" "https://www.winbond.com/resource-files/w25q128jv%20revf%2003272018%20plus.pdf")
    (property "symbolName1" "W25Q128JVPIQ_TR")
)
